CS_App/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('ColorSurvey.urls',namespace="ColorSurvey")),
]

ColorSurvey/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'ColorSurvey'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout,name='logout'),
    url(r'^language_view/$',views.language_view, name='language_view'),
    url(r'^language/add/$', views.language_add,name='language_add'),
    url(r'^language/edit/(?P<language_id>\d+)/$',views.language_edit,name='language_edit'),
    url(r'^language/delete/(?P<language_id>\d+)/$',views.language_delete,name='language_delete'),
    url(r'^language_profile/(?P<language_id>\d+)/$',views.language_profile,name='language_profile'),
    url(r'^color_terms/list/(?P<language_id>\d+)/$',views.list_color_terms,name='list_color_terms'),
    url(r'^color_terms/edit/(?P<color_term_id>\d+)/$',views.edit_color_terms,name='edit_color_terms'),
    url(r'^color_terms/delete/(?P<color_term_id>\d+)/$',views.delete_color_terms,name='delete_color_terms'),
    url(r'^color_terms/survey/home$',views.survey_home, name='survey_home'),
    url(r'^color_terms/survey/start/(?P<language_id>\d+)/(?P<color_id>\d+)$',views.color_terms_survey_startpage,name='color_terms_survey_startpage'),
    url(r'^color_terms/survey/(?P<language_id>\d+)/(?P<color_id>\d+)$',views.color_terms_survey,name='color_terms_survey'),
    url(r'^color_terms/survey/end$',views.survey_end, name='survey_end'),
    url(r'^color_terms/add/(?P<language_id>\d+)/$',views.add_color_terms,name='add_color_terms'),
    url(r'^color_db_data/add/$',views.color_db_data, name='color_db_data'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ColorSurvey/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import validate_comma_separated_integer_list

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

class language(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    l_name = models.CharField(max_length = 100, null = False, unique = True)
    def __unicode__(self):
      return self.l_name

class color_term(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    language_id = models.ForeignKey(language, on_delete=models.CASCADE)
    color = models.CharField(max_length=100, null = False, unique = True)
    meaning = models.TextField(blank = False)
    seed_color = models.CharField(max_length=100)
    value_lab = models.CharField(max_length=100, blank = True, null = True, validators=[validate_comma_separated_integer_list])

    def __unicode__(self):
      return self.color

class color_data(models.Model):
    value_lab = models.CharField(max_length=100, null = False, unique = True, validators=[validate_comma_separated_integer_list])
    value_rgb = models.CharField(max_length=100, null = False, unique = True, validators=[validate_comma_separated_integer_list])
    color_tile = models.ImageField('img',upload_to='ColorData/')

class survey_data(models.Model):
    user_id = models.ForeignKey(User,on_delete = models.CASCADE)
    language_id = models.ForeignKey(language, on_delete = models.CASCADE)
    color_term_id = models.ForeignKey(color_term, null = True, on_delete = models.CASCADE)
    selected_colors = models.CharField(max_length=200, null = True, validators=[validate_comma_separated_integer_list])

ColorSurvey/forms.py
from ColorSurvey.models import UserProfile
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django import forms
from .models import color_term, language, color_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if not password or not confirm_password:
            raise ValidationError("Invalid password")
        if password != confirm_password:
            raise ValidationError("Password confirmation failed")
        return confirm_password

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website',)

class LanguageForm(forms.ModelForm):
    class Meta:
        model = language
        fields = ('l_name',)
        labels = {"l_name": "Language Name"}

class ColorTermForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ColorTermForm, self).__init__(*args, **kwargs)
        self.fields['seed_color'].widget.attrs['readonly'] = True
    class Meta:
        model = color_term
        fields = ('color','meaning','seed_color')

class ColorDataForm(forms.ModelForm):
    class Meta:
        model = color_data
        fields = ('value_lab','value_rgb','color_tile')

ColorSurvey/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader,RequestContext
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import auth, messages
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from skimage import color
from django.core.files import File
import os, urllib, scipy, numpy, ast

from ColorSurvey.models import language, color_term, color_data, survey_data
from ColorSurvey.forms import UserForm, UserProfileForm, LanguageForm, ColorTermForm, ColorDataForm

from views_user_auth import *


'''
==============================================================================
Methods for all the functional features of the website
==============================================================================
'''

@login_required(login_url='ColorSurvey:login')
def index(request):
    if request.user.is_authenticated():
        login_status = 1
    else:
        login_status = 0
    template = loader.get_template('index.html')
    context = {'login_status':login_status}
    return HttpResponse(template.render(context, request))

@login_required(login_url='ColorSurvey:login')
def language_add(request):
    current_user = request.user
    if request.method=='POST':
        form = LanguageForm(request.POST)
        if form.is_valid():
            new_language = form.save(commit=False)
            new_language.user_id = request.user
            new_language.save()
            return HttpResponseRedirect(reverse('ColorSurvey:language_view'))
    else:
        form = LanguageForm()
    context = {'form':form}
    template = loader.get_template('language_add.html')
    return HttpResponse(template.render(context, request))

@login_required(login_url='ColorSurvey:login')
def language_edit(request,language_id):
    context = {}
    language_obj = get_object_or_404(language, pk = language_id)
    if request.method=='GET':
        form = LanguageForm(instance=language_obj)
        context = {'form':form}
    else:
        form = LanguageForm(request.POST, instance = language_obj)
        if form.is_valid():
            language_obj = form.save(commit = False)
            language_obj.save()
            return HttpResponseRedirect(reverse('ColorSurvey:language_view'))
    template = loader.get_template('language_edit.html')
    return HttpResponse(template.render(context,request))

@login_required(login_url='ColorSurvey:login')
def language_delete(request,language_id):
    language_obj = get_object_or_404(language,pk=language_id)
    language_obj.delete()
    return HttpResponseRedirect(reverse('ColorSurvey:language_view'))

@login_required(login_url='ColorSurvey:login')
def language_view(request):
    current_user = request.user
    obj = language.objects.filter(user_id=current_user)
    context = {'language_list':obj}
    template = loader.get_template('language_view.html')
    return HttpResponse(template.render(context,request))

@login_required(login_url='ColorSurvey:login')
def language_profile(request,language_id):
    current_user = request.user
    temp_lang_id = int(language_id)
    language_obj = language.objects.get(id = temp_lang_id)
    total_terms = color_term.objects.filter(user_id = current_user).filter(language_id = temp_lang_id).count()
    context = {'language_obj':language_obj,'total_terms':total_terms}
    template = loader.get_template('language_profile.html')
    return HttpResponse(template.render(context, request))

@login_required(login_url='ColorSurvey:login')
def list_color_terms(request,language_id):
    current_user = request.user
    temp_lang_id = int(language_id)
    try:
        obj = language.objects.filter(user_id = current_user).get(id = temp_lang_id)
    except language.DoesNotExist:
        obj = None
        user_languages = language.objects.filter(user_id = current_user)
        context = {'user_languages':user_languages}
        template = loader.get_template('error.html')
        return HttpResponse(template.render(context, request))

    color_term_obj = color_term.objects.filter(user_id = current_user).filter(language_id = temp_lang_id)

    context = {"color_terms_list":color_term_obj}
    template = loader.get_template('list_color_terms.html')
    return HttpResponse(template.render(context,request))

@login_required(login_url='ColorSurvey:login')
def add_color_terms(request,language_id):
    current_user = request.user
    form = ColorTermForm(request.POST)
    temp_lang_id = int(language_id)

    try:
        obj = language.objects.filter(user_id = current_user).get(id = temp_lang_id)
    except language.DoesNotExist:
        obj = None
        user_languages = language.objects.filter(user_id = current_user)
        context = {'user_languages':user_languages}
        template = loader.get_template('error.html')
        return HttpResponse(template.render(context, request))

    if request.method=='POST':
        if form.is_valid():
            new_color_term = form.save(commit=False)
            new_color_term.user_id = request.user

            seed_color_rgb_raw = new_color_term.seed_color #value of seed_color_rgb_raw is #ABCDEF
            seed_color_rgb_raw = list(seed_color_rgb_raw) #value of seed_color_rgb_raw is [#,A,B,C...]

            rgb_color = [[[0.0,0.0,0.0]]]
            j = 0
            result_hex_rgb = []
            # This for loog tries to get "AB","CD","EF" from [#,A,B,C...] as corressponding RGB values
            for i in range(1,6,2):
                s = ""
                # extracting 'A' and 'B' from the array [#,A,B,C...]
                seq = (seed_color_rgb_raw[i],seed_color_rgb_raw[i+1])
                # joining unicode 'A' and 'B' as string 'AB' and appending it to result_hex_rgb
                result_hex_rgb.append(str(s.join(seq)))
                rgb_color[0][0][j] = float(int(result_hex_rgb[j],16))/256
                j = j + 1

            lab_color = color.rgb2lab(rgb_color)
            new_color_term.value_lab = [lab_color[0][0][0], lab_color[0][0][1], lab_color[0][0][2]]

            new_color_term.language_id = obj
            new_color_term.save()
            return HttpResponseRedirect(reverse('ColorSurvey:add_color_terms',args=[language_id,]))
    else:
        form = ColorTermForm()
    context = {'form':form}
    template = loader.get_template('color_terms.html')
    return HttpResponse(template.render(context, request))

@login_required(login_url='ColorSurvey:login')
def edit_color_terms(request,color_term_id):
    current_user = request.user
    form = ColorTermForm(request.POST)
    context = {}
    color_term_object = get_object_or_404(color_term, pk = color_term_id)
    if request.method=='GET':
        form = ColorTermForm(instance = color_term_object)
        initial_color = color_term_object.seed_color
        print form
        context = {'form':form, 'initial_color':initial_color}
    else:
        form = ColorTermForm(request.POST, instance = color_term_object)
        if form.is_valid():
            color_term_object = form.save(commit = False)
            seed_color_rgb_raw = color_term_object.seed_color #value of seed_color_rgb_raw is #ABCDEF
            seed_color_rgb_raw = list(seed_color_rgb_raw) #value of seed_color_rgb_raw is [#,A,B,C...]

            rgb_color = [[[0.0,0.0,0.0]]]
            j = 0
            result_hex_rgb = []
            # This for loog tries to get "AB","CD","EF" from [#,A,B,C...] as corressponding RGB values
            for i in range(1,6,2):
                s = ""
                # extracting 'A' and 'B' from the array [#,A,B,C...]
                seq = (seed_color_rgb_raw[i],seed_color_rgb_raw[i+1])
                # joining unicode 'A' and 'B' as string 'AB' and appending it to result_hex_rgb
                result_hex_rgb.append(str(s.join(seq)))
                rgb_color[0][0][j] = float(int(result_hex_rgb[j],16))/256
                j = j + 1

            lab_color = color.rgb2lab(rgb_color)
            color_term_object.value_lab = [lab_color[0][0][0], lab_color[0][0][1], lab_color[0][0][2]]

            color_term_object.save()
            language_id = color_term_object.language_id.id
            return HttpResponseRedirect(reverse('ColorSurvey:list_color_terms',args=[language_id,]))
    template = loader.get_template('color_terms_edit.html')
    return HttpResponse(template.render(context,request))

@login_required(login_url='ColorSurvey:login')
def delete_color_terms(request,color_term_id):
    color_term_object = get_object_or_404(color_term,pk=color_term_id)
    language_id = color_term_object.language_id.id
    color_term_object.delete()
    return HttpResponseRedirect(reverse('ColorSurvey:list_color_terms',args=[language_id,]))

'''
==============================================================================
************************** DO NOT USE THIS FUNCTION **************************
This function is used for feeding the data-set of 5572 color-tiles in the
database model named "color_data"
==============================================================================
'''

@login_required(login_url='ColorSurvey:login')
def color_db_data(request):
    #This function feeds the dataset of all 5572 colors into the sql database.
    f_rgb = open('ColorData/rgb1.txt')
    line_rgb = f_rgb.readline()

    f_lab = open('ColorData/lab.txt')
    line_lab = f_lab.readline()
    i = 1

    # The os.listdir() returns random ordered list. To have ordered list: 1.jpg, 2.jpg, 3.jpg ...,
    # we have to first convert unicode list to string list and then use sorted() function
    sorted_dir_list = sorted(os.listdir("ColorData/"))

ColorSurvey/templates/base.html
{% load staticfiles %}
<html>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

    <head>
        <title>ColorSurvey</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Carter One' rel='stylesheet'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>

    <style>
    #grad1
    {
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
        height: 55px;
        background: -webkit-linear-gradient(left, red, orange, yellow, green, blue, indigo, violet); /* For Safari 5.1 to 6.0 */
        background: -o-linear-gradient(left, red, orange, yellow, green, blue, indigo, violet); /* For Opera 11.1 to 12.0 */
        background: -moz-linear-gradient(left, red, orange, yellow, green, blue, indigo, violet); /* For Fx 3.6 to 15 */
        background: linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet); /* Standard syntax (must be last) */
        border-radius: 15px;
    }

    #nav_items
    {
        color: white;
    }

    .nav_select:hover
    {
        box-shadow: 3px 3px 15px white;
        zoom: 1;
        filter: alpha(opacity=100);
        opacity: 1;
    }
    </style>

    <body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="grad1" style="color: white; font-family: 'Carter One';font-size: 22px;" class="navbar-brand" href="{% url 'ColorSurvey:index' %}"><b>ColorSurvey</b></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a class="nav_select" id="nav_items" href="{% url 'ColorSurvey:index' %}">Home</a></li>
                    <li><a class="nav_select" id="nav_items" href="{% url 'ColorSurvey:language_view' %}">Languages</a></li>
                    <li><a class="nav_select" id="nav_items" href="{% url 'ColorSurvey:language_add' %}">Add</a></li>
                    <li><a class="nav_select" id="nav_items" href="{% url 'ColorSurvey:survey_home' %}">Survey</a></li>
                </ul>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a id="nav_items" href="{% url 'ColorSurvey:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout </a></li>
                    {% else %}
                    <li><a id="nav_items" href="{% url 'ColorSurvey:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up </a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    </body>
</html>

ColorSurvey/templates/color_data.html
{% extends 'base.html' %}

{% block content %}
        <h1>Color Data</h1>
{% endblock %}

ColorSurvey/templates/color_terms_edit.html
{% extends 'base.html' %}

{% block content %}

<script language="javascript">

function newBackgroundColor(color)
{
    //document.bgColor = color;
    document.ColorForm.seed_color.value = color;
}
</script>

<style>
table, th, td {
    border: 1px solid black;
}
th, td {
    padding: 15px;
}
</style>

<div class="panel panel-primary">
    <div class="panel-heading">Edit color-term</div>
</div>


<div class="well well-lg">

    <form name="ColorForm" action="" method='post' enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <div class="field form-group">
            {{form.as_p}}
            <p>Selected Seed Color
            <input name="colorpicker" type="color" value={{initial_color}} onchange="newBackgroundColor(colorpicker.value);">
            </p>
        </div>
        {{form.errors}}
        <div class="form-group">
            <input type="submit" name="save_color_term" class="btn btn-primary" value="Update">
        </div>
    </form>

</div>

{% endblock %}

ColorSurvey/templates/color_terms_survey.html
{% extends 'base.html' %}


{% block content %}

<script type="text/javascript">

function null_validation()
{
    if($('[name="tag"]:checkbox:checked').length == 0)
    {
        alert("Please select atleast one color.");
        return false;

    }
    return true;

}
</script>

    <div class="panel panel-primary">
      <div class="panel-heading"><h1>{{color_term_object.color}}</h1></div>
      <div class="panel-body"><h3>{{color_term_object.meaning}}</h3></div>
    </div>

    <form name="ColorSurveyForm" action="{% url 'ColorSurvey:color_terms_survey' temp_lang_id next_color_id %}" method='post'
                enctype="multipart/form-data" class="form-horizontal" onsubmit="return null_validation()" >
        {% csrf_token %}
        <div style="">
            {% for iter in options_list %}
            <div style="text-align: center; display:inline-block; margin: 0; border: 3px solid black;">
                <p><img src="{{iter.color_tile.url}}" alt="image" height="100" width="100"></p>
                <p> {{iter.id}} </p>
                <p><input type="checkbox" name="tag" id="{{iter.id}}" value="{{iter.id}}"></p>
            </div>
            {% empty %}
            <div>Sorry, no records in this list.</div>
            {% endfor %}
        </div>
        {{form.errors}}
        <br>
        <div class="form-group" style="text-align:center">
            <input type="submit" name="save_color_term_survey" class="btn btn-primary" value="Next" >
        </div>
    </form>

{% endblock %}

ColorSurvey/templates/color_terms_survey_startpage.html
{% extends 'base.html' %}

<style>

</style>

{% block content %}

    <div class="panel panel-primary">
      <div class="panel-heading"><h4>Instructions to Color Survey participants</h4></div>
      <div class="panel-body"><h5>Time Required: 45 min</h5></div>
    </div>

    <div class="well well-lg">
        <h3>Note:</h3>
        <ol>
            <li>The survey assumes that the participant is fluent in the survey language.</li>
            <li>The "color-term" will be displayed at the top of the screen.</li>
            <li>Participant may look at the meanings of the corressponding color-term displayed on the screen if they are not familiar with the word.</li>
            <li>Select the colour swatches that represent the name by clicking on them. Participants may select more than one of them. </li>
            <li>Click on "Next" to submit your selection and go to the next colour-term. </li>
            <li>The selection cannot be modified once submitted. </li>
            <li>An acknowledgement page will confirm the end of survey once all the color-terms are finished. </li>
            <li>Click on "Start Survey" to begin the Color Survey. </li>
        </ol>
    </div>

    <a href="{% url 'ColorSurvey:color_terms_survey' language_id color_id %}">
        <button type="button" class="btn btn-primary">Start Survey</button>
    </a>


{% endblock %}

ColorSurvey/templates/edit_color_terms.html
{% extends 'base.html' %}

{% block content %}

<script language="javascript">
function newBackgroundColor(color)
{
    //document.bgColor = color;
    document.ColorForm.seed_color.value = color;
}
</script>

<style>
table, th, td {
    border: 1px solid black;
}
th, td {
    padding: 15px;
}
</style>

<div class="panel panel-primary">
    <div class="panel-heading">Add color-term</div>
</div>


<div class="well well-lg">

    <form name="ColorForm" action="" method='post' enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <div class="field form-group">
            <table style="width:100%">
                <tr>
                    <th>Color Term</th>
                    <td><input type="text" class="form-control" placeholder="Enter color-term here." name="color" id="color"></td>
                </tr>
                <tr>
                    <th>Meaning</th>
                    <td><input type="text" class="form-control" placeholder="Enter dictionary meaning here." name="meaning" id="meaning"></td>
                </tr>
                <tr>
                    <th>Seed Color</th>
                    <td>
                        <p>Selected Seed Color
                        <input name="colorpicker" type="color" onchange="newBackgroundColor(colorpicker.value);">
                        </p>
                        <input type="text" class="form-control" placeholder="Select seed-color using the given picker." name="seed_color" id="seed_color">
                    </td>
                </tr>
            </table>
        </div>
        {{form.errors}}
        <div class="form-group">
            <input type="submit" name="save_color_term" class="btn btn-primary" value="Save">
        </div>
    </form>

</div>

{% endblock %}

ColorSurvey/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading"><h4>Home</h4></div>
    </div>

    <div class="well well-lg">
        <h5>Welcome {{ user.username }},</h5>
        This is ColorSurvey App for data-collection, survey and analysis of color-terms in various languages. 
        It is a simple 3-step process:
        <br>
        <div class="panel panel-info">
            <div class="panel-heading"> Step 1 </div>
            <div class="panel-body">Add the language for ColorSurvey</div>
        </div>

        <div class="panel panel-warning">
            <div class="panel-heading"> Step 2 </div>
            <div class="panel-body">Populate the color-terms with meanings and seed-colors</div>
        </div>

        <div class="panel panel-danger">
            <div class="panel-heading"> Step 3 </div>
            <div class="panel-body"> Perform the ColorSurvey on the language and analyze the results</div>
        </div>
    </div>
{% endblock %}

ColorSurvey/templates/language_add.html
{% extends 'base.html' %}

{% block content %}

    <div class="panel panel-primary">
      <div class="panel-heading"><h4>Add New Language</h4></div>
    </div>

    <div class="well well-lg">
        <form action="" method='post' enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            <div class="form-group">
            {{ form.as_p }}
            <input type="submit" name="save_language" class="btn btn-primary" value="Add">
        </form>
    </div>

{% endblock %}

ColorSurvey/templates/list_color_terms.html
{% extends 'base.html' %}

{% block content %}

<style>
table, th, td {
    border: 1px solid black;
}
th, td {
    padding: 15px;
}
</style>

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myList tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<div class="panel panel-primary">
    <div class="panel-heading">List of color-terms</div>
</div>

<div class="well well-sm">
    <input class="form-control" id="myInput" type="text" placeholder="Search Color Term">
</div>

<div class="well well-lg">
    <table style="width:100%" class="list-group" id="myList">
        <tr>
            <th>Color Term</th>
            <th>Meaning</th>
            <th>Seed Color</th>
            <th> </th>
            <th> </th>
        </tr>
        {% for iter in color_terms_list %}
        <tr>
            <td>{{iter.color}}</td>
            <td>{{iter.meaning}}</td>
            <td>{{iter.seed_color}}</td>
            <td bgcolor={{iter.seed_color}}></td>
            <td>
                <a href="{% url 'ColorSurvey:delete_color_terms' color_term_id=iter.id %}">
                <button style="float: right;" type="button" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                </button></a>

                <a href="{% url 'ColorSurvey:edit_color_terms' color_term_id=iter.id %}">
                <button style="float: right;" type="button" class="btn btn-info">
                    <span class="glyphicon glyphicon-edit"></span>
                </button></a>
            </td>
        </tr>
        {% empty %}
        <td>Sorry, no records in this list.</td>
        {% endfor %}
    </table>
</div>

{% endblock %}

ColorSurvey/templates/survey_end.html
{% extends 'base.html' %}

{% block content %}

    <div class="panel panel-primary">
      <div class="panel-heading"><h4>Thank You :)</h4></div>
      <div class="panel-body"><h5>Color Survey is now complete.</h5></div>
    </div>

    <a href="{% url 'ColorSurvey:index' %}">
        <button type="button" class="btn btn-primary">Finish</button>
    </a>

{% endblock %}

ColorSurvey/templates/survey_home.html
{% extends 'base.html' %}

{% block content %}

  <div class="panel panel-primary">
    <div class="panel-heading"><h4>Color Survey Home</h4></div>
    <div class="panel-body"><h5>Available Languages</h5></div>
  </div>

  <div class="well well-lg">
    {% for lang_id, lang_name,color_id in survey_list %}
        <h3>
        <a href="{% url 'ColorSurvey:color_terms_survey_startpage' lang_id color_id %}"><strong>{{lang_name}}</strong></a>
        </h3>
    {% endfor %}
  </div>

{% endblock %}